gui:
  theme:
    selectedLineBgColor:
      - underline
    selectedRangeBgColor:
      - underline
git:
  pagers:
    - pager: delta --dark --paging=never
  disableForcePushing: true
customCommands:
  - key: '≈ù'
    context: 'global'
    command: 'kill "$PPID"'
  - key: 'G'
    context: 'global'
    command: 'zsh -ci gh-switch'
os:
  editPreset: 'nvim'
